name: random workflow
on: [push]

jobs:
    linux-command-output:
        runs-on: ubuntu-latest
        name: output of command
        steps:
          - name: Run commands
            run: |
              echo "hi i am here"
              touch abc.txt
              echo "Random Number: $RANDOM"
              echo "Current Date and Time: $(date)"
              ip a
