name: Test API
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    services:
      app:
        image: alialaa17/simple-node-api
        ports:
          - 3000:3000
        env:
          MONGO_HOSTNAME: mongo
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Install curl
        run: apt-get update && apt-get install -y curl
      - name: Wait for Service
        run: sleep 10  # Adjust the sleep duration based on the time needed for your service to start.
      - name: Dump Services Context
        run: echo '${{ toJson('services') }}'
      - name: Post a User
        run: |
          curl -X POST http://localhost:3000/api/users -H "Content-Type: application/json" -d '{"username": "hello", "address": "dwded"}'
      - name: Get Users
        run: curl http://localhost:3000/api/users
